name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3

      - name: Create environment
        run: $CONDA/bin/conda create --yes --name mm2image python=3.10 wxpython=4.2.1 --channel conda-forge

      - name: Install dependencies
        run: $CONDA/envs/mm2image/bin/pip install -r requirements.txt

      - name: Install dev dependencies
        run: $CONDA/envs/mm2image/bin/pip install -r dev-requirements.txt

      - name: Create binary
        run: |
          $CONDA/envs/mm2image/bin/pyinstaller --clean --onefile --noconsole --noconfirm --dist ./dist/linux ./mm2image.py

      - name: Zip binary
        run: |
          cd ./dist/linux
          zip mm2image-linux.zip mm2image

      - uses: actions/upload-artifact@v3
        with:
          name: mm2image-linux
          path: ./dist/linux/mm2image-linux.zip

  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3

      - name: Create environment and install dependencies
        run: $CONDA/bin/conda create --yes --name mm2image python=3.10 wxpython=4.2.1 --channel conda-forge

      - name: Install dependencies
        run: $CONDA/envs/mm2image/bin/pip install -r requirements.txt

      - name: Install dev dependencies
        run: $CONDA/envs/mm2image/bin/pip install -r dev-requirements.txt

      - name: Create binary
        run: |
          $CONDA/envs/mm2image/bin/pyinstaller --clean --onefile --noconsole --noconfirm --dist ./dist/macos ./mm2image.py
          rm -rf ./dist/macos/mm2image

      - name: Zip binary
        run: |
          cd ./dist/macos
          zip -r mm2image-macos.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: mm2image-macos
          path: ./dist/macos/mm2image-macos.zip

  windows:
    runs-on: windows-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo %CONDA%
        shell: cmd

      - name: Create environment and install dependencies
        run: |
          %CONDA%\Scripts\conda.exe create ^
          --yes --name mm2image python=3.10 wxpython=4.2.1 --channel conda-forge
        shell: cmd

      - name: Install dependencies
        run: |
          %CONDA%\envs\mm2image\Scripts\pip install -r requirements.txt
        shell: cmd

      - name: Install dev dependencies
        run: |
          %CONDA%\envs\mm2image\Scripts\pip install -r dev-requirements.txt
        shell: cmd

      - name: Create binary
        run: |
          %CONDA%\envs\mm2image\Scripts\pyinstaller.exe ^
          --clean --onefile --noconsole --noconfirm --dist .\dist\windows64 .\mm2image.py
        shell: cmd

      - name: Zip binary
        run: |
          cd .\dist\windows64
          powershell Compress-Archive mm2image.exe mm2image-windows.zip

      - uses: actions/upload-artifact@v3
        with:
          name: mm2image-windows64
          path: .\dist\windows64\mm2image-windows.zip
